language: node_js
node_js: 10
os: osx

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.4
      install:
        - ./scripts/install.ios.sh
      script:
        - ./scripts/ci.ios.sh

before_install:
  - nvm install 8