source 'https://github.com/CocoaPods/Specs.git'

target 'Basic' do
  pod 'React', subspecs: [
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ], path: '../node_modules/react-native'

  pod 'react-native-idfa',  path: '../node_modules/@ptomasroos/react-native-idfa/'
end
